version: '3'
services:

  rabbit:
    image: rabbitmq:3.7-management
    hostname: rabbit
    container_name: "rabbitmq37"
    restart: always
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:3
    container_name: "redis3"
    # command: redis-server --requirepass 123456 使用配置文件
    restart: always
    ports:
      - 16379:6379
    volumes: 
      - ./data/redis:/data
      - ./redis/redis.conf:/etc/redis.conf

  mysql:
    image: mysql:5.7.23
    restart: always
    container_name: "mysql57"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
    ports:
      - 13306:3306
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./mysql/mymysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

  postgresdb:
    restart: always
    container_name: "postgresdb96"
    image: postgres:9.6.2
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata

  elasticsearch:
    container_name: elasticsearch654
    build: ./es/
    volumes: 
      - ./data/es6.5:/usr/share/elasticsearch/data
      - ./es/es.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: 
      - 19300:9300
      - 19200:9200
    networks:
      - esnet

  kibana:
    build: ./kibana/
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    container_name: kibana654
    hostname: kibana
    networks:
      - esnet
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "15601:5601"

networks:
  esnet:
    driver: bridge
