version: '2'
services:
  mysql5.6:
    image: mysql:5.6
    ports:
      - "3306:3306"
    container_name: my-mysql
    hostname: my-mysql
    volumes:
      - /home/config/mysql/lib/data:/var/lib/mysql
      - /home/config/mysql/logs:/logs
      - /home/config/mysql/data:/usr/data
    environment:
      MYSQL_ROOT_PASSWORD : zhen
      MYSQL_DATABASE: maitao
      MYSQL_USER: maitao
      MYSQL_PASSWORD: maitao

  redis4.0:
    image: redis:4.0
    container_name: my-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    hostname: my-redis
    volumes:
      - /home/config/redis/data:/data

  elasticsearch2.4.6:
    image:  library/elasticsearch:2.4.6
    container_name: my-es 
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes: 
      - /home/config/elasticsearch/data:/usr/share/elasticsearch/data
      - /home/config/elasticsearch/config:/usr/share/elasticsearch/config
      - /home/config/elasticsearch/logs:/usr/share/elasticsearch/logs
    hostname: my-es

  rabbitmq3.6.10:
    image: rabbitmq:3.6.10-management
    container_name: my-rabbit
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672" 
      - "4369:4369"
      - "5671:5671"
      - "15671:15671"
      - "25672:25672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/home/LIVE/rabbitmq/
# Config file /etc/rabbitmq/rabbitmq.config
# Database directory  /var/lib/rabbitmq/mnesia/rabbit@my-rabbit
# - /home/config/mysql/conf/my.cnf:/etc/mysql/my.cnf
  build: 
    container_name: my-build
    image:  daocloud.io/dasy/demo:test1
    tty: true
    hostname: my-build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /opt/release:/opt/jar/release
