version: '2'
services:
  mysql5.6:
    image: mysql:5.6
    ports:
      - "3306:3306"
    container_name: my-mysql
    hostname: my-mysql
    volumes:
      - /home/LIVE/mysql/lib/data:/var/lib/mysql
      - /home/LIVE/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - /home/LIVE/mysql/logs:/logs
      - /home/LIVE/mysql/data:/mysql_data
    environment:
      MYSQL_ROOT_PASSWORD : zhen
      MYSQL_DATABASE: maitao
      MYSQL_USER: maitao
      MYSQL_PASSWORD: maitao

  redis4.0:
    image: redis:4.0
    container_name: my-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    hostname: my-redis
    volumes:
      - /home/LIVE/redis/data:/data

  elasticsearch2.4.6:
    image: es2.4.6
    container_name: my-es
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes: 
      - /home/LIVE/elasticsearch/data:/usr/share/elasticsearch/data
    hostname: my-es

  rabbitmq3.6.10:
    image: rabbitmq:3.6.10-management
    container_name: my-rabbit
    ports:
      - "15672:15672"
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672" 
      - "4369:4369"
      - "5671:5671"
      - "15671:15671"
      - "25672:25672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/home/LIVE/rabbitmq/

  web:
    container_name: my-web
    image:  daocloud.io/dasy/demo:test
    ports: 
      - "9999:9999" 
      - "8888:8888" 
      - "8806:8806" 
      - "8866:8866"  
      - "8809:8809"  
      - "8091:8091"  
      - "8092:8092"  
      - "8093:8093" 
      - "8090:8090"  
      - "8999:8999" 
      - "9411:9411"  
      
      # - "9999:9999" #registry
      # - "8888:8888" #config
      # - "8806:8806" #maitao-dashbord
      # - "8866:8866" #maitao-sercice
      # - "8809:8809" #maitao-turbin
      # - "8091:8091" #service-common
      # - "8092:8092" #service-product
      # - "8093:8093" #service-user
      # - "8090:8090" #service-batch
      # - "8999:8999" #gatway
      # - "9411:9411" #zipkin
    tty: true
    hostname: my-web
    links:
      - mysql5.6
      - redis4.0
      - elasticsearch2.4.6
      - rabbitmq3.6.10
    volumes:
      - /home/LIVE/web/logs:/opt/logs
